version: '3.8'
services:
  db:
    restart: always
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./config/.env

  bot:
    restart: always
    build: .
    command: >
      sh -c "python main.py"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env
    depends_on:
      - db

volumes:
  postgres_data:
